// packages/vue/components/VirtualList.vue
<template>
  <div class="virtual-list__client" ref="clientRefEl" data-id="client">
    <div class="list-body__container">
      <div
        v-if="$slots.stickyHeader"
        ref="stickyHeaderRefEl"
        :class="`virtual-list__sticky-header ${stickyHeaderClass}`"
        :style="stickyHeaderStyle"
        data-id="stickyHeader"
      >
        <slot name="stickyHeader"></slot>
      </div>
      <div class="virtual-list-body" ref="listRefEl">
        <div
          v-if="$slots.header"
          ref="headerRefEl"
          :class="headerClass"
          :style="headerStyle"
          data-id="header"
        >
          <slot name="header"></slot>
        </div>
        <div class="list-body__content">
          <ObserverItem
            v-for="(item, index) in renderList"
            :key="item[itemKey]"
            :id="item[itemKey]"
            :resizeObserver="virtualListIns?.resizeObserver"
          >
            <template #default>
              <slot
                :data="item"
                :index="virtualListIns!.listState.renderBegin + index"
              ></slot>
            </template>
          </ObserverItem>
        </div>
        <div
          v-if="$slots.footer"
          ref="footerRefEl"
          :class="footerClass"
          :style="footerStyle"
          data-id="footer"
        >
          <slot name="footer"></slot>
        </div>
      </div>
      <div
        v-if="$slots.stickyFooter"
        ref="stickyFooterRefEl"
        :class="`virtual-list__sticky-footer ${stickyFooterClass}`"
        :style="stickyFooterStyle"
        data-id="stickyFooter"
      >
        <slot name="stickyFooter"></slot>
      </div>
    </div>
    <Scrollbar
      v-if="!disableScrollbar"
      :direction="
        horizontal ? ScrollbarDirection.HORIZONTAL : ScrollbarDirection.VERTICAL
      "
      :clientSize="virtualListState.clientSize"
      :listSize="
        virtualListState.listTotalSize +
        virtualListState.headerSize +
        virtualListState.footerSize
      "
      :scrollFrom="
        virtualListState.offset /
        (virtualListState.listTotalSize +
          virtualListState.headerSize +
          virtualListState.footerSize -
          virtualListState.clientSize)
      "
      :onScroll="onScrollBarScroll"
      :bgColor="scrollbarBgColor"
      :thumbClass="scrollbarThumbClass"
      :trickerClass="scrollbarTrickerClass"
      :thumbStyle="scrollbarThumbStyle"
      :trickerStyle="scrollbarTrickerStyle"
    ></Scrollbar>
  </div>
</template>

<script lang="ts" setup>
import { ScrollbarDirection } from 'virtual-list-core';
import ObserverItem from './ObserverItem.vue';
import Scrollbar from './Scrollbar.vue';
import { useVirtualList } from '../hooks/useVirtualList';
import { IVirtualListProps, VirtualListEmitEvents } from '../types';

const props = withDefaults(
  defineProps<IVirtualListProps<Record<string, any>>>(),
  {
    itemKey: 'id',
  },
);
const emits = defineEmits<{
  (e: VirtualListEmitEvents.SCROLL, offset: number): void;
  (
    e: VirtualListEmitEvents.SCROLL_TO_TOP,
    firstItem: Record<string, any>,
  ): void;
  (
    e: VirtualListEmitEvents.SCROLL_TO_BOTTOM,
    lastItem: Record<string, any>,
  ): void;
}>();

const {
  clientRefEl,
  listRefEl,
  headerRefEl,
  footerRefEl,
  stickyHeaderRefEl,
  stickyFooterRefEl,
  renderList,
  virtualListIns,
  virtualListState,
  onScrollBarScroll,
  scrollToIndex,
  scrollToOffset,
  scrollToTop,
  scrollToBottom,
  scrollIntoView,
} = useVirtualList(props, emits);

defineExpose<{
  scrollToIndex: (index: number) => void;
  scrollToOffset: (offset: number) => void;
  scrollToTop: () => void;
  scrollToBottom: () => void;
  scrollIntoView: (index: number) => void;
  virtualListIns: typeof virtualListIns;
}>({
  scrollToIndex,
  scrollToOffset,
  scrollToTop,
  scrollIntoView,
  scrollToBottom,
  virtualListIns,
});
</script>

<style scoped>
.virtual-list__client {
  width: 100%;
  height: 100%;
  position: relative;
}
.list-body__container {
  height: 100%;
  width: 100%;
  overflow: auto hidden;
}
.virtual-list-body {
  will-change: transform;
}
.virtual-list__sticky-header {
  position: sticky;
  top: 0;
  z-index: 2;
}
.virtual-list__sticky-footer {
  position: sticky;
  bottom: 0;
  z-index: 2;
}
</style>

// packages/react/src/components/VirtualList.tsx
import {
  useEffect,
  useRef,
  type CSSProperties,
  type RefObject,
  type ReactNode,
} from 'react';
import { useVirtualList } from '../hooks/useVirtualList';
import type { IObserverItemProps, IVirtualListProps } from '../types';
import { VirtualScrollbar } from './Scrollbar';
import '../styles/index.css';
import { ScrollbarDirection } from 'virtual-list-core';

export const ObserverItem = (props: IObserverItemProps) => {
  const { id, resizeObserver, customRender } = props;

  const observerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const currentObserverRef = observerRef.current;
    if (currentObserverRef) {
      resizeObserver?.observe(currentObserverRef);
    }

    return () => {
      if (currentObserverRef) {
        resizeObserver?.unobserve(currentObserverRef);
      }
    };
  }, [resizeObserver]);

  return (
    <div ref={observerRef} data-id={id}>
      {customRender()}
    </div>
  );
};

export const VirtualList = (props: IVirtualListProps<Record<string, any>>) => {
  const {
    header,
    footer,
    content,
    scrollbar,
    stickyHeader,
    stickyFooter,
    horizontal,
    headerClass,
    headerStyle,
    footerClass,
    footerStyle,
    stickyFooterClass,
    stickyFooterStyle,
    stickyHeaderClass,
    stickyHeaderStyle,
    disableScrollbar,
    scrollbarBgColor,
    scrollbarThumbClass,
    scrollbarThumbStyle,
    scrollbarTrickerClass,
    scrollbarTrickerStyle,
  } = props;

  const {
    clientRefEl,
    listRefEl,
    headerRefEl,
    footerRefEl,
    stickyHeaderRefEl,
    stickyFooterRefEl,
    offset,
    clientSize,
    listTotalSize,
    headerSize,
    footerSize,
    renderList,
    virtualListIns,
    onScrollBarScroll,
  } = useVirtualList(props);

  const renderChild = (options: {
    childRef: RefObject<HTMLDivElement>;
    childClass: string | undefined;
    childStyle: CSSProperties | undefined;
    child: (() => ReactNode) | undefined;
  }) => {
    const { child, childRef, childClass, childStyle } = options;
    return child ? (
      <div ref={childRef} className={childClass} style={childStyle}>
        {child()}
      </div>
    ) : null;
  };

  const renderContent = () => {
    return (
      <div className="list-body__content">
        {renderList.map((item, index) => {
          return (
            <ObserverItem
              id={item.id}
              key={item.id}
              resizeObserver={
                virtualListIns
                  ? virtualListIns.current?.resizeObserver
                  : undefined
              }
              customRender={() => content?.(item, index)}
            ></ObserverItem>
          );
        })}
      </div>
    );
  };

  const renderScrollbar = () => {
    if (disableScrollbar) return null;
    if (scrollbar) return scrollbar();

    return (
      <VirtualScrollbar
        direction={
          horizontal
            ? ScrollbarDirection.HORIZONTAL
            : ScrollbarDirection.VERTICAL
        }
        listSize={listTotalSize + headerSize + footerSize}
        scrollFrom={
          offset / (listTotalSize + headerSize + footerSize - clientSize)
        }
        clientSize={clientSize}
        bgColor={scrollbarBgColor}
        thumbClass={scrollbarThumbClass}
        thumbStyle={scrollbarThumbStyle}
        trickerClass={scrollbarTrickerClass}
        trickerStyle={scrollbarTrickerStyle}
        onScroll={onScrollBarScroll}
      />
    );
  };

  return (
    <div className="virtual-list__client" ref={clientRefEl} data-id="client">
      <div className="list-body__container">
        {renderChild({
          childRef: stickyHeaderRefEl,
          childClass: `virtual-list__sticky-header ${stickyHeaderClass}`,
          childStyle: stickyHeaderStyle,
          child: stickyHeader,
        })}
        <div className="list-body" ref={listRefEl}>
          {renderChild({
            childRef: headerRefEl,
            childClass: headerClass,
            childStyle: headerStyle,
            child: header,
          })}
          <div className="list-body__content">{renderContent()}</div>
          {renderChild({
            childRef: footerRefEl,
            childClass: footerClass,
            childStyle: footerStyle,
            child: footer,
          })}
        </div>
        {renderChild({
          childRef: stickyFooterRefEl,
          childClass: `virtual-list__sticky-footer ${stickyFooterClass}`,
          childStyle: stickyFooterStyle,
          child: stickyFooter,
        })}
      </div>
      {renderScrollbar()}
    </div>
  );
};
