// packages/vue/components/Scrollbar.vue
<template>
  <div class="scrollbar-container" ref="trickRef">
    <div class="scrollbar-item" ref="thumbRef"></div>
  </div>
</template>

<script lang="ts" setup>
import { onMounted, ref, watch } from 'vue';
import {
  Scrollbar,
  ScrollbarEvent,
  type ScrollbarDirection,
} from 'virtual-list-core';

const props = defineProps<{
  direction: ScrollbarDirection;
  clientSize: number;
  listSize: number;
  scrollFrom: number;
  bgColor?: string;
  thumbClass?: string;
  trickerClass?: string;
  thumbStyle?: Record<string, string | number>;
  trickerStyle?: Record<string, string | number>;
}>();

const emits = defineEmits<{
  (e: 'scroll', offsetRa: number): void;
}>();

const scrollbarIns = ref<Scrollbar | null>(null);

const thumbRef = ref<HTMLElement | null>(null);
const trickRef = ref<HTMLElement | null>(null);

watch(
  () => props.clientSize,
  (newSize) => {
    scrollbarIns.value?.updateClientSize(newSize);
  },
);

watch(
  () => props.listSize,
  () => {
    scrollbarIns.value?.updateListSize(props.listSize);
  },
);

watch(
  () => props.scrollFrom,
  () => {
    scrollbarIns.value?.updateScrollFrom(props.scrollFrom);
  },
);

onMounted(() => {
  scrollbarIns.value = new Scrollbar(
    {
      thumbEl: thumbRef.value!,
      trickerEl: trickRef.value!,
      direction: props.direction,
      clientSize: props.clientSize,
      listSize: props.clientSize,
      scrollFrom: props.scrollFrom,
      bgColor: props.bgColor,
      thumbClass: props.thumbClass,
      trickerClass: props.trickerClass,
      thumbStyle: props.thumbStyle,
      trickerStyle: props.trickerStyle,
    },
    {
      [ScrollbarEvent.SCROLL]: (offsetRatio: number) =>
        emits('scroll', offsetRatio),
    },
  );
});
</script>
<style scoped>
.scrollbar-container .scrollbar-item {
  position: absolute;
  border-radius: 5px;
  z-index: 11;
  opacity: 0.3;
}
.scrollbar-container .scrollbar-item:hover {
  opacity: 0.5;
  cursor: pointer;
}
</style>

// packages/react/components/Scrollbar.tsx
import { Scrollbar, ScrollbarEvent } from 'virtual-list-core';
import { useEffect, useRef } from 'react';
import { IScrollbarProps } from '../types';
import '../styles/scrollbar.css';

export const VirtualScrollbar = (props: IScrollbarProps) => {
  const {
    direction,
    clientSize,
    listSize,
    scrollFrom,
    bgColor,
    thumbClass,
    trickerClass,
    thumbStyle,
    trickerStyle,
    onScroll,
  } = props;
  const scrollbarIns = useRef<Scrollbar | null>(null);

  const thumbRef = useRef<HTMLDivElement | null>(null);
  const trickRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    scrollbarIns.current = new Scrollbar(
      {
        thumbEl: thumbRef.current!,
        trickerEl: trickRef.current!,
        direction: direction,
        clientSize: clientSize,
        listSize: clientSize,
        scrollFrom: scrollFrom,
        bgColor: bgColor,
        thumbClass: thumbClass,
        trickerClass: trickerClass,
        thumbStyle: thumbStyle,
        trickerStyle: trickerStyle,
      },
      {
        [ScrollbarEvent.SCROLL]: (offsetRatio: number) => {
          onScroll?.(offsetRatio);
        },
      },
    );
    return () => {
      if (scrollbarIns.current) {
        scrollbarIns.current.destroy();
        scrollbarIns.current = null;
      }
    };
  }, [
    bgColor,
    clientSize,
    direction,
    onScroll,
    scrollFrom,
    thumbClass,
    thumbStyle,
    trickerClass,
    trickerStyle,
  ]);

  useEffect(() => {
    scrollbarIns.current?.updateClientSize(clientSize);
  }, [clientSize]);

  useEffect(() => {
    scrollbarIns.current?.updateListSize(listSize);
  }, [listSize]);

  useEffect(() => {
    scrollbarIns.current?.updateScrollFrom(scrollFrom);
  }, [scrollFrom]);

  return (
    <div
      className={`scrollbar-container ${trickerClass}`}
      ref={trickRef}
      style={trickerStyle}
    >
      <div
        className={`scrollbar-item ${thumbClass}`}
        ref={thumbRef}
        style={thumbStyle}
      ></div>
    </div>
  );
};
